spring:
  application:
    name: coffee

  profiles:
    default: local

  datasource:
    #url: jdbc:h2:mem:~/coffee_db
    url: jdbc:h2:tcp://localhost/~/coffee
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-profile: local

  sql:
    init:
      mode: EMBEDDED
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
